name: Pass inputs
on: push
env: 
  y: 10
jobs:
  run_Script:
    env:
      y: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Codew
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: run script
        env:
          a: 5
          b: 30
        run: |
          echo "Worflow level z=$z"
          echo "Job level y=$y"
          echo "Step level a=$a"
          python Scripts/practice.py ${{ env.b }} $a