name : Variables
on:
  workflow_dispatch:
env:
  name: "JOhn"
jobs:
  test:
    env:
      school: "Minerva"
    runs-on: ubuntu-latest
    steps:
     - name: job1
       env: 
          class: "seventh"
       run: |  
        echo "$name studying $class standard in $school ${{ vars.projectname }}"
        echo "Actor: ${{ github.actor }}"
        echo "Repo: ${{ github.repository }}"
        echo "Event: ${{ github.event_name }}"
        echo "Branch: ${{ github.ref }}"
        echo "OS: ${{ runner.os }}"
        echo "Name: ${{ env.NAME }}"


       